/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run update-md-schema.cmd to regenerate this file.
 */

/**
 * The event or state-change that initiates the transition.
 */
export type Trigger = StateTrigger | EventTrigger;
/**
 * The trigger for this combination.
 */
export type Trigger1 = StateTrigger | EventTrigger;
/**
 * The trigger for this combination.
 */
export type Trigger2 = StateTrigger | EventTrigger;
/**
 * JSON Schema for the AST output generated by the state machine parser.
 */
export type StateMachines = StateMachine[];

/**
 * The full representation of a parsed *.state-machine.md file.
 */
export interface StateMachine {
  /**
   * The title of the state machine (from the H1 heading).
   */
  name: string;
  /**
   * A brief description of the state machine's purpose.
   */
  overview?: string | null;
  /**
   * The absolute path to the source markdown file.
   */
  source?: string | null;
  /**
   * A list of all valid states for this machine.
   *
   * @minItems 1
   */
  states: [StateDefinition, ...StateDefinition[]];
  /**
   * The state in which the machine starts.
   */
  initialState?: string;
  /**
   * Data attributes associated with the state machine. Keyed by attribute name, mapping to the attribute description.
   */
  data?: {
    [k: string]: string;
  };
  /**
   * Examples of data combinations, either synthesized from inline examples or explicitly defined in a combination table. By schema convention, an empty string value encodes an undefined/absent value for that attribute.
   */
  dataExampleValues?: {
    [k: string]: string;
  }[];
  /**
   * Additional data values declared in the 'Other values:' table. These are behaviorally equivalent to the example values from a state machine perspective and exist to enrich the value pool for data modifiers such as 'not', 'other', or 'different'. By schema convention, an empty string value encodes an undefined/absent value for that attribute.
   */
  dataOtherValues?: {
    [k: string]: string;
  }[];
  /**
   * Default precondition states declared in the Transitions section under 'Default preconditions:'. Each entry is a state name whose owning machine is resolved at generation time. The state is prepended as a Given precondition step for every transition that does not already mention a state from the same machine.
   */
  defaultPreconditions?: DefaultPrecondition[];
  /**
   * Optional transition table defining how the machine moves between states based on triggers. When omitted, this is equivalent to an empty array.
   */
  transitions?: Transition[];
  impossible?: ImpossibleSection;
  /**
   * Explicitly declared combinations where triggers produce the same outcome regardless of the listed state.
   */
  irrelevant?: IrrelevantTrigger[];
}
/**
 * A state belonging to this state machine.
 */
export interface StateDefinition {
  /**
   * The plain text name of the state, with emphasis markup removed.
   */
  name: string;
  /**
   * Optional description providing additional info about the state.
   */
  description?: string | null;
  /**
   * Data value conditions implied by this state, declared as indented sub-bullets in the state definition.
   */
  impliedConditions?: ImpliedCondition[];
  /**
   * The 1-based line number within the source file defining this state.
   */
  sourceLine?: number | null;
}
/**
 * A data value condition implied by being in a particular state (from an implied-condition sub-bullet).
 */
export interface ImpliedCondition {
  /**
   * The data attribute name.
   */
  attribute: string;
  condition: Condition;
}
/**
 * The value condition that holds when the state is active.
 */
export interface Condition {
  /**
   * The condition operator. The 'undefined' operator is unary and carries no value.
   */
  operator:
    | "="
    | "<>"
    | "<"
    | ">"
    | "<="
    | ">="
    | "as"
    | "not as"
    | "in"
    | "not in"
    | "in range"
    | "not in range"
    | "undefined";
  /**
   * The literal value or array of values for the condition. Absent when operator is 'undefined'.
   */
  value?: string | string[];
}
/**
 * A single default precondition state entry, used in the 'Default preconditions:' block of a Transitions section.
 */
export interface DefaultPrecondition {
  /**
   * The plain text name of the default precondition state.
   */
  state: string;
  /**
   * Optional data attributes associated with this default precondition state. Inherited from the markdown `Default preconditions:` block when the entry carries inline backtick arguments.
   */
  arguments?: Argument[];
  /**
   * Optional description providing additional info about the default precondition.
   */
  description?: string;
}
/**
 * A data attribute reference, mapped from backticks in the text, with optional qualifiers, modifiers, or conditions. The `qualifier` property and the `modifier` property are mutually exclusive: an argument uses either `qualifier` alone (simple form) or `modifier` with optional `preQualifier`/`postQualifier` (modified form), never both.
 */
export interface Argument {
  /**
   * A qualifying preposition (e.g. 'for', 'as') placed before the backtick reference when no modifier is present. Mutually exclusive with `modifier`.
   */
  qualifier?: string;
  /**
   * A preposition (e.g. 'for', 'as') preceding the modifier. Only used with `modifier`, not with `qualifier`.
   */
  preQualifier?: string;
  /**
   * A keyword describing the relationship between this value and the value elsewhere (e.g. 'not', 'different', 'next', 'incremented'). Mutually exclusive with `qualifier`.
   */
  modifier?: string;
  /**
   * Text following the modifier, used for sentence structuring. Only used with `modifier`, not with `qualifier`.
   */
  postQualifier?: string;
  /**
   * The name of the data attribute being referenced.
   */
  name: string;
  condition?: Condition1;
  /**
   * Plain words following the backtick argument span (after any post-qualifier), used for human-readable sentence continuations such as 'prefilled' or 'only'.
   */
  suffix?: string;
}
/**
 * A value condition constraining the attribute to a specific subset of its possible values.
 */
export interface Condition1 {
  /**
   * The condition operator. The 'undefined' operator is unary and carries no value.
   */
  operator:
    | "="
    | "<>"
    | "<"
    | ">"
    | "<="
    | ">="
    | "as"
    | "not as"
    | "in"
    | "not in"
    | "in range"
    | "not in range"
    | "undefined";
  /**
   * The literal value or array of values for the condition. Absent when operator is 'undefined'.
   */
  value?: string | string[];
}
/**
 * A single transition definition describing how the machine moves between states.
 */
export interface Transition {
  /**
   * Unique numeric identifier for this transition (e.g. '123'). Optional in test fixtures; assigned by the parser or renumber command when missing.
   */
  id?: string;
  /**
   * Optional combined precondition states: external preconditions plus the machine's own precondition state. When omitted, this is equivalent to an empty array.
   */
  states?: StateRef[];
  trigger: Trigger;
  result: StateRef1;
  /**
   * Additional context or side effects for the transition. Optional.
   */
  notes?: string;
  /**
   * The 1-based line number within the source file defining this transition.
   */
  sourceLine?: number | null;
}
/**
 * A reference to a state (either internal or external), potentially with data arguments.
 */
export interface StateRef {
  /**
   * The plain text name of the state.
   */
  name: string;
  /**
   * Optional data attributes associated with this state reference.
   */
  arguments?: Argument[];
}
/**
 * A trigger that fires when another machine enters a specific state.
 */
export interface StateTrigger {
  /**
   * Discriminator value identifying this as a state trigger.
   */
  type: "state";
  /**
   * The name of the state.
   */
  name: string;
  /**
   * Optional data attributes associated with this trigger.
   */
  arguments?: Argument[];
}
/**
 * A trigger representing an external event driven by an action.
 */
export interface EventTrigger {
  /**
   * Discriminator value identifying this as an event trigger.
   */
  type: "event";
  /**
   * The plain text name of the event.
   */
  name: string;
  /**
   * Optional data attributes associated with this trigger.
   */
  arguments?: Argument[];
}
/**
 * A reference to a state (either internal or external), potentially with data arguments.
 */
export interface StateRef1 {
  /**
   * The plain text name of the state.
   */
  name: string;
  /**
   * Optional data attributes associated with this state reference.
   */
  arguments?: Argument[];
}
/**
 * Impossible trigger and state combinations, grouped by origin.
 */
export interface ImpossibleSection {
  /**
   * Explicitly declared impossible trigger and state combinations.
   */
  defined: ImpossibleTrigger[];
  /**
   * Impossible trigger and state combinations derived by the infer step, absent when only the parser output is present.
   */
  inferred?: ImpossibleTrigger[];
}
/**
 * A row declaring an impossible state-trigger combination.
 */
export interface ImpossibleTrigger {
  /**
   * The preconditions/states that make this combination impossible.
   */
  states: string[];
  trigger: Trigger1;
}
/**
 * A row declaring an irrelevant state-trigger combination.
 */
export interface IrrelevantTrigger {
  /**
   * The preconditions/states that make this combination irrelevant.
   */
  states: string[];
  trigger: Trigger2;
}
