const fs = require('fs');
const path = require('path');
// const parseMd = require('json-schema-to-markdown');
const { compileFromFile } = require('json-schema-to-typescript');

const schemaPath = path.join(__dirname, 'sm.ast.schema.json');
const mdOutputPath = path.join(__dirname, 'sm.ast.schema.md');
const tsOutputPath = path.join(__dirname, 'sm.ast.d.ts');

// Generate Markdown
// const schemaStr = fs.readFileSync(schemaPath, 'utf8');
// const schema = JSON.parse(schemaStr);
// const markdown = parseMd(schema);
// fs.writeFileSync(mdOutputPath, markdown);
// console.log(`Successfully generated Markdown in ${mdOutputPath}`);

// Generate TypeScript
compileFromFile(schemaPath, {
    bannerComment: '/* tslint:disable */\n/**\n* This file was automatically generated by json-schema-to-typescript.\n* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,\n* and run update-md-schema.cmd to regenerate this file.\n*/'
}).then(ts => {
    fs.writeFileSync(tsOutputPath, ts);
    console.log(`Successfully generated TypeScript in ${tsOutputPath}`);
}).catch(err => {
    console.error('Failed to generate TypeScript:', err);
    process.exit(1);
});
